### ISSUE TITLE
When will it be supported on Stellar Expert?

### ISSUE THREAD

**Issue by alejomendoza** [orbitlens/stellar-dynamic-asset-metadata-server#1]
Hello @orbitlens! here is skyhitz's asset metadata [server](https://api.skyhitz.io/api/assets) and the [toml](https://skyhitz.io/.well-known/stellar.toml). We implemented SEP-14 but it seems like there isn't that much support for it out there.  Thanks!

**Comment by orbitlens** [comment]
Hello,

SEP-14 is already supported on the server side for quite some time. I checked the errors log for your domain and it shows two parsing errors:
- several times your `stellar.toml` file was inaccessible (errored after 10s timeout)
- the resizing script on your server randomly returns "Error 9524: image could not be resized (200)", for example  at https://skyhitz.io/cdn-cgi/image/width=200/https://cloudflare-ipfs.com/ipfs/bafybeidkwybme35dejzdxbr6k73he4ujy5y5dhfhweckcetfk2hoxas2py

Both errors occur randomly and not very frequent, but our parser at some point removed your domain from the parsing queue after several repeats. I kicked the re-indexing and made corresponding changes to better handle such situations in the future.
You can see that we already show icons for your assets.

As for the full metadata information in the UI, it should be released by the end of this week, with a huge TOML meta-releted update we've been prepraring for quite some time.

**Comment by alejomendoza** [comment]
Hey @orbitlens thanks for your reply, we managed to fix the error we were getting with cloudflare for the images, we had to switch to another service (pinata). Images should work now on stellar.expert, does this re-indexing happens everyday? let me know if you can run it again. Best!

**Comment by orbitlens** [comment]
Hey,

Happy to hear that you resolved the images hosting problem. Our crawler scans all known domains for changes every 24 hours. If the TOML file is not changed, further processing is skipped. This doesn't apply to Dynamic Metadata Server endpoint which gets reindexed every 24 hours.

I just checked and it looks like your domain has been reindexed recently.

Please let me know if you spot any issues. The indexer code for this logic has been rigorously tested internally but real world often brings surprises.

**Comment by alejomendoza** [comment]
Thanks! I see it working now :)
